apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-tomcat
  namespace: retail
  labels:
    app: customer-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-tomcat
  template:
    metadata:
      labels:
        app: customer-tomcat
    spec:
      containers:
        - name: customer-tomcat
          image: quay.io/konveyor/example-1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: customer-db
                  key: jdbc-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-db
                  key: password
          envFrom:
            - configMapRef:
                name: customer-config
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
      imagePullSecrets:
        - name: registry-credentials
